import Head from "next/head";
import { useState, useEffect } from "react";
import Input from "../components/input";
import Button from "../components/button";
import Notification from "../components/notification";

import { SearchAndReplaceContent } from "../services/search";

export default function Home() {
  const [token, setToken] = useState("");
  const [searchTerm, setSearchTerm] = useState("");
  const [replacement, setReplacement] = useState("");

  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [showNotification, setShowNotification] = useState(false);

  const handleCloseNotification = () => {
    setShowNotification(false);
  };

  const handleSubmit = async () => {
    if (!searchTerm || !replacement || !token) {
      setErrorMsg("Please fill out all fields");
      setShowNotification(true);
      return;
    }

    setLoading(true);
    try {
      await SearchAndReplaceContent(searchTerm, replacement, token);
      setReplacement("");
      setSearchTerm("");
      setErrorMsg("");
      setShowNotification(true);
    } catch (error: any) {
      setErrorMsg(error?.response?.data?.message || error?.message);
      setShowNotification(true);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const timer = setTimeout(handleCloseNotification, 3000);

    return () => clearTimeout(timer);
  }, [errorMsg, showNotification]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <Notification
          isError={!!errorMsg}
          show={showNotification}
          message={errorMsg || "Successfully Replaced!!!"}
          handleClose={handleCloseNotification}
        />
        <Input
          value={searchTerm}
          type="text"
          name="search_term"
          placeholder="Search Term"
          onChange={(e) => setSearchTerm(e.target.value)}
        />
        <Input
          value={replacement}
          type="text"
          name="replacement"
          placeholder="Replacement"
          onChange={(e) => setReplacement(e.target.value)}
        />
        <Input
          value={token}
          type="text"
          name="token"
          placeholder="Space Token"
          onChange={(e) => setToken(e.target.value)}
        />
        <div className="pt-5">
          <Button disabled={loading} label="Submit" onClick={handleSubmit} />
        </div>
      </div>
    </>
  );
}
